{"uuid": "11632e6f-d21c-4563-abb2-eb14ad6b8bab", "children": ["a19243dc-cd9f-46ae-9f57-f6146d29d39d"], "befores": [{"name": "login_user_1", "status": "broken", "statusDetails": {"message": "AttributeError: module 'api.user' has no attribute 'login'\n", "trace": "  File \"e:\\workspace\\pytestDemo\\.venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"e:\\workspace\\pytestDemo\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"e:\\workspace\\pytestDemo\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"E:\\workspace\\pytestDemo\\testcases\\conftest.py\", line 23, in login_user_1\n    res = user.login(data=payload, headers=header)\n"}, "start": 1722495191911, "stop": 1722495191911}], "start": 1722495191911, "stop": 1722495192014}