{"uuid": "a529dde5-4d74-4710-ae79-2b73747cebd6", "children": ["8a9de51a-e79b-456d-8473-b36077582fb4"], "befores": [{"name": "login_user_1", "status": "broken", "statusDetails": {"message": "AttributeError: 'Response' object has no attribute 'response'\n", "trace": "  File \"e:\\workspace\\pytestDemo\\.venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"e:\\workspace\\pytestDemo\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"e:\\workspace\\pytestDemo\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"E:\\workspace\\pytestDemo\\testcases\\conftest.py\", line 33, in login_user_1\n    logger.info(\"登录用户 ==>> 返回结果 ==>> {}\".format(res.response.text))\n"}, "start": 1722508548972, "stop": 1722508549796}], "start": 1722508548972, "stop": 1722508549824}