{"uuid": "fc93d59c-4415-47c8-8e56-1cb98612b018", "children": ["cb6391dd-b98d-42b0-81aa-23856afc2b3a"], "befores": [{"name": "login_user_1", "status": "broken", "statusDetails": {"message": "AttributeError: module 'api.user' has no attribute 'login'\n", "trace": "  File \"e:\\workspace\\pytestDemo\\.venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"e:\\workspace\\pytestDemo\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"e:\\workspace\\pytestDemo\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"E:\\workspace\\pytestDemo\\testcases\\conftest.py\", line 23, in login_user_1\n    res = user.login(data=payload, headers=header)\n"}, "start": 1722495227657, "stop": 1722495227657}], "start": 1722495227657, "stop": 1722495227688}